package com.cts.ms.location.dao;
// Generated Sep 17, 2017 1:00:28 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Locationconfig generated by hbm2java
 */
@Entity
@Table(name="locationconfig"
    ,catalog="`sfdc-poc-location`"
)
public class Locationconfig  implements java.io.Serializable {


     private String locationId;
     private String status;

    public Locationconfig() {
    }

    public Locationconfig(String locationId, String status) {
       this.locationId = locationId;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="LocationId", unique=true, nullable=false, length=100)
    public String getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    
    @Column(name="Status", nullable=false, length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


