---
server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          #uri: D:/SKG/JAVA_DEVELOPMENT/SFDC-POC-DEV
          uri: https://github.com/saibalghosh1980/MS-SFDC-PoC
          searchPaths: ALLCONFIG
management:
  security:
    enabled: false