package com.cts.ms.location.dao;
// Generated Sep 13, 2017 11:22:27 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Locationconfig generated by hbm2java
 */
@Entity
@Table(name = "locationconfig", catalog = "`sfdc-poc`")
public class Locationconfig implements java.io.Serializable {

	private String id;
	private String status;

	public Locationconfig() {
	}

	public Locationconfig(String id, String status) {
		this.id = id;
		this.status = status;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Status", nullable = false, length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
